baseURL = "https://js2264.github.io/NGS-analysis_Physalia_2021/"
publishDir = "docs"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "NGS analysis for gene regulation and epigenomics"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/js2264/NGS-analysis_Physalia_2021/blob/master/content/"
  packageBaseUrl = "NGS-analysis_Physalia_2021/"
  description = "NGS analysis for gene regulation and epigenomics"
  author = "Jacques Serizay"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"
  themeVariant = "red"
  ordersectionsby = "title"
  disableSearch = true

[blackfriday]
  hrefTargetBlank = true
